# Generated by Django 5.1.6 on 2025-04-09 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='prodImagePath',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
