# Generated by Django 5.1.5 on 2025-07-15 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_management', '0004_product_uploaduser'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='moderation_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
