# Generated by Django 5.1.5 on 2025-07-15 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_management', '0005_product_moderation_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='approved',
        ),
    ]
