# Generated by Django 5.1.5 on 2025-07-15 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_management', '0006_remove_product_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='prodOnMenu',
        ),
    ]
