# Generated by Django 5.1.6 on 2025-03-28 20:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout_management', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction_log',
            name='cartId',
        ),
        migrations.AddField(
            model_name='transaction_log',
            name='datetimeUpdated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='transaction_log',
            name='menuCartItems',
            field=models.JSONField(default=dict, help_text='Dictionary where keys are MENU item IDs and values are quantities'),
        ),
        migrations.AddField(
            model_name='transaction_log',
            name='paymentMethod',
            field=models.CharField(choices=[('cash', 'Cash'), ('card', 'Card')], default='card', help_text='Payment method used for the transaction', max_length=10),
        ),
        migrations.AddField(
            model_name='transaction_log',
            name='user',
            field=models.OneToOneField(default=9, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
